// bitmap-font.js — pixel-perfect text renderer for the canvas UI.
//
// Why this exists: browser canvas text via ctx.fillText uses anti-aliased
// system fonts, which fight the pixel-art aesthetic and look mushy at
// small sizes (the HP "100/100" and hotbar numbers were the worst
// offenders). This module renders text from a pre-baked white-on-
// transparent glyph atlas (game/assets/font_8x8.png, generated by
// tools/gen_font.py), tinted to any color at draw time.
//
// Atlas layout: 16 cols × 6 rows of 8×8 cells, covering printable ASCII
// 32-126. Glyph index for codepoint C = (C - 32). Out-of-range codepoints
// render as the '?' glyph fallback.

const GLYPH_W = 8;
const GLYPH_H = 8;
const COLS = 16;
const ROWS = 6;

export class BitmapFont {
    constructor(atlasImg) {
        this.atlas = atlasImg;
        // Pre-render the atlas into per-color cache canvases keyed by color
        // string. Tinting via globalCompositeOperation each draw is hot-path
        // expensive; instead we cache a single tinted copy per color used.
        this._tintCache = new Map();
    }

    static async load(srcUrl) {
        const img = new Image();
        img.src = srcUrl;
        await new Promise((res, rej) => { img.onload = res; img.onerror = rej; });
        return new BitmapFont(img);
    }

    // Get (or build) a colored copy of the atlas. The original is
    // white-on-transparent; we paint a colored rect over a copy and use
    // destination-in to keep only the glyph pixels.
    _getTinted(color) {
        const cached = this._tintCache.get(color);
        if (cached) return cached;
        const c = document.createElement('canvas');
        c.width = this.atlas.width;
        c.height = this.atlas.height;
        const cx = c.getContext('2d');
        cx.imageSmoothingEnabled = false;
        // 1. Fill the canvas with the target color
        cx.fillStyle = color;
        cx.fillRect(0, 0, c.width, c.height);
        // 2. Keep only pixels that are non-transparent in the atlas
        cx.globalCompositeOperation = 'destination-in';
        cx.drawImage(this.atlas, 0, 0);
        cx.globalCompositeOperation = 'source-over';
        this._tintCache.set(color, c);
        return c;
    }

    // Width in pixels of `text` at the given scale. Glyphs are fixed-width
    // 8×8; we render with the full 8 columns per glyph (the trailing column
    // is mostly empty by design so adjacent glyphs don't touch).
    measure(text, scale = 1) {
        return text.length * GLYPH_W * scale;
    }

    // Draw `text` with its top-left at (x, y). Options:
    //   color  — CSS color string, default '#fff'
    //   scale  — integer scale factor, default 1 (so each pixel = 1)
    //   shadow — CSS color for a 1-pixel drop shadow, default none
    //   align  — 'left' (default), 'center', or 'right' for x anchoring
    drawText(ctx, text, x, y, opts = {}) {
        const {
            color  = '#ffffff',
            scale  = 1,
            shadow = null,
            align  = 'left',
        } = opts;
        const width = this.measure(text, scale);
        let ox = x;
        if (align === 'center') ox = x - width / 2;
        else if (align === 'right') ox = x - width;
        // Snap to integer pixels so anti-aliasing-free rendering stays crisp.
        ox = Math.round(ox);
        const oy = Math.round(y);

        const draw = (px, py, tintedAtlas) => {
            for (let i = 0; i < text.length; i++) {
                const code = text.charCodeAt(i);
                let idx = code - 32;
                if (idx < 0 || idx >= 95) idx = 63 - 32; // fallback to '?'
                const col = idx % COLS;
                const row = Math.floor(idx / COLS);
                ctx.drawImage(
                    tintedAtlas,
                    col * GLYPH_W, row * GLYPH_H, GLYPH_W, GLYPH_H,
                    px + i * GLYPH_W * scale, py,
                    GLYPH_W * scale, GLYPH_H * scale,
                );
            }
        };

        // Preserve image-smoothing setting (the canvas may be in smooth mode
        // for sprite work; we always want crisp text).
        const wasSmoothing = ctx.imageSmoothingEnabled;
        ctx.imageSmoothingEnabled = false;
        if (shadow) {
            draw(ox + scale, oy + scale, this._getTinted(shadow));
        }
        draw(ox, oy, this._getTinted(color));
        ctx.imageSmoothingEnabled = wasSmoothing;
    }
}

export const GLYPH_SIZE = { w: GLYPH_W, h: GLYPH_H };
