// renderer.js — Final pass: pixel art world + parchment UI
// Large panels: 9-slice from Modern UI Style 1
// Small panels: hand-colored parchment fill matching the sprite palette
// All text: dark brown on parchment for readability (not gold-on-dark)

import { TILE_PX, VIEW_TILES, CANVAS_PX, INVENTORY_SIZE } from './data.js';
import { TILE_SPRITE_MAP, TOWN_TILE_SPRITE_MAP, ZONE_TILE_SPRITE_MAP, ENEMY_SPRITES, ITEM_SPRITES, PLAYER_SPRITE } from './sprites.js';
import { UI, ITEM_COLORS, drawPanelBig, drawPanelSmall, drawInset } from './ui-sprites.js';

export class Renderer {
    constructor(canvas) {
        this.canvas = canvas;
        this.ctx    = canvas.getContext('2d');
        canvas.width  = CANVAS_PX;
        canvas.height = CANVAS_PX;
        this.ctx.imageSmoothingEnabled = false;

        this.half    = (VIEW_TILES - 1) / 2;
        this.sprites = null;
        this.zone    = 'TOWN';
    }

    // The 9-slice panel atlas. Was a dead-loaded `uiStyle1` reference (no
    // matching Kenney sheet ever shipped), so drawPanelBig has been falling
    // back to flat-color rectangles since v0.4-ish. The new `uiPanel` sheet
    // is generated by tools/gen_ui_panel.py and contains base/dark/glow
    // variants stacked vertically.
    get uiSheet() { return this.sprites?.uiPanel ?? null; }

    // ── Splash ───────────────────────────────────────────────────────────────

    renderSplash(splashCanvas) {
        const ctx = splashCanvas.getContext('2d');
        splashCanvas.width = 320;
        splashCanvas.height = 220;
        ctx.imageSmoothingEnabled = false;

        ctx.fillStyle = '#0e0c08';
        ctx.fillRect(0, 0, 320, 220);

        const ui = this.uiSheet;
        if (ui?.loaded) {
            drawPanelBig(ctx, ui, 16, 12, 288, 196);
        } else {
            ctx.fillStyle = UI.panelBg;
            ctx.fillRect(20, 16, 280, 188);
            ctx.strokeStyle = UI.panelBorder;
            ctx.lineWidth = 2;
            ctx.strokeRect(20, 16, 280, 188);
        }

        // Small game-name header — bitmap font, centered horizontally
        if (this.font) {
            this.font.drawText(ctx, 'VIOLENCETOWN', 160, 32, {
                color: UI.panelBorder, scale: 1, align: 'center',
            });
        }

        // Horizontal rule under header
        ctx.strokeStyle = UI.panelBorder;
        ctx.lineWidth = 1;
        ctx.beginPath(); ctx.moveTo(90, 44); ctx.lineTo(230, 44); ctx.stroke();

        // Cityscape silhouette — replaces an earlier character lineup that
        // read as three skin-tone variants. Procedural noir skyline drawn
        // directly: dark buildings with scattered window dots and a low moon.
        // Reads as "a place bigger than you, mostly hostile, occasionally lit".
        // Anchored inside the panel from y=56 down to y=130.
        this._drawSplashCityscape(ctx);

        // Big GAME START prompt — the centerpiece. Scale 3 = 24px tall.
        if (this.font) {
            this.font.drawText(ctx, 'GAME START', 160, 148, {
                color: UI.panelBorder, scale: 3, align: 'center',
            });

            // Subtitle hint
            this.font.drawText(ctx, 'PRESS SPACE OR CLICK BELOW', 160, 178, {
                color: UI.textLight, scale: 1, align: 'center',
            });
        }

        // Version — read from <meta name="version"> so it's a single source of truth
        const meta = typeof document !== 'undefined'
            ? document.querySelector('meta[name="version"]')
            : null;
        const version = meta ? meta.getAttribute('content') : '?';
        if (this.font) {
            // y=192 sits above the panel's bottom 16px-cell trim/accents at
            // y≈193+. Right-anchored 24px in from the panel's right edge
            // (which lives at x≈304); left-anchored 24px in from the left.
            this.font.drawText(ctx, 'V' + version, 280, 192, {
                color: UI.textLight, scale: 1, align: 'right',
            });
            this.font.drawText(ctx, 'BY CAELAN GANDER', 32, 192, {
                color: UI.textLight, scale: 1, align: 'left',
            });
        }
    }

    // ── Splash cityscape ─────────────────────────────────────────────────────
    //
    // A procedural neo-noir skyline that fills the splash's middle band. The
    // intent: convey "a savage town, bigger than you, with a few lit windows
    // that hint at the lives behind every wall." Drawn purely with rects so
    // it scales pixel-perfect at any preview size and never depends on an
    // asset that might not load.
    //
    // Composition (within the panel's 288×196 interior, anchored at x≈16,
    // y≈12 on the 320×220 splash canvas):
    //   - Sky band:   y=56..130
    //   - Far row:    short dim silhouettes (back layer)
    //   - Near row:   taller silhouettes with window dots (front layer)
    //   - Moon:       a small ochre disk top-right, partially behind near row
    //
    // Building positions/heights are seeded from a fixed pattern so the
    // splash always renders the same — recruiters who reload see a stable
    // composition, not a random one. The pattern is keyed to the canvas
    // x-coordinate so it tiles cleanly within the panel.

    _drawSplashCityscape(ctx) {
        const PANEL_X = 24, PANEL_W = 272;
        const SKY_Y = 56, SKY_H = 76;
        const GROUND_Y = SKY_Y + SKY_H;

        // Sky — dark band that contrasts with the parchment so the silhouettes
        // read as foreground. A subtle horizontal gradient (top darker, bottom
        // browner) suggests a hazy late-night downtown.
        ctx.fillStyle = '#1a1410';
        ctx.fillRect(PANEL_X, SKY_Y, PANEL_W, SKY_H);
        ctx.fillStyle = '#26190f';
        ctx.fillRect(PANEL_X, GROUND_Y - 18, PANEL_W, 18);

        // Moon — small ochre disk, behind the near-row silhouettes.
        // Aproximated with 5 stacked rects so it stays crisp at every scale.
        const moonX = PANEL_X + PANEL_W - 56, moonY = SKY_Y + 12;
        const moonRects = [[2,0,4,1],[1,1,6,1],[0,2,8,4],[1,6,6,1],[2,7,4,1]];
        ctx.fillStyle = '#d4b96a';
        for (const [dx, dy, w, h] of moonRects) {
            ctx.fillRect(moonX + dx, moonY + dy, w, h);
        }

        // Far-row buildings — short, dim, no windows. Provides depth.
        // Heights cycle through a 6-step pattern keyed to building index.
        const FAR_H = [10, 14, 8, 16, 12, 10];
        const FAR_W = 14;
        const farY0 = GROUND_Y - 20;
        ctx.fillStyle = '#2a1e14';
        for (let i = 0; PANEL_X + i * FAR_W < PANEL_X + PANEL_W; i++) {
            const h = FAR_H[i % FAR_H.length];
            const bx = PANEL_X + i * FAR_W;
            ctx.fillRect(bx, farY0 - h, FAR_W, h + 20);
        }

        // Near-row buildings — taller, varied widths, window dots. The
        // pattern is deliberately uneven so the skyline reads as a real
        // city block, not a periodic texture.
        // Each tuple: [width, height, windowsPerRow, windowRows]
        const NEAR_PATTERN = [
            [22, 38, 3, 5], [16, 28, 2, 3], [28, 52, 4, 7], [14, 22, 1, 2],
            [24, 44, 3, 6], [18, 32, 2, 4], [30, 58, 4, 8], [20, 36, 2, 5],
            [14, 26, 1, 3], [26, 48, 3, 6],
        ];
        let bx = PANEL_X;
        let i = 0;
        ctx.fillStyle = '#100a08';
        while (bx < PANEL_X + PANEL_W) {
            const [bw, bh, wPerRow, wRows] = NEAR_PATTERN[i % NEAR_PATTERN.length];
            const by = GROUND_Y - bh;
            // Building body
            ctx.fillRect(bx, by, bw, bh + 8); // +8 lets it run past the ground line
            // Top-edge highlight (one pixel lighter) — gives the silhouette
            // a slight glint that suggests the moon is grazing the rooftops.
            ctx.fillStyle = '#3a2a18';
            ctx.fillRect(bx, by, bw, 1);
            ctx.fillStyle = '#100a08';
            // Window dots — small 1×1 ochre marks, evenly spaced.
            // Skip a deterministic ~20% so the windows look lived-in (some
            // dark, some lit) rather than a perfect grid.
            const wPadX = 3, wPadY = 6;
            const wSpaceX = (bw - wPadX * 2 - wPerRow) / Math.max(1, wPerRow - 1) || 0;
            const wSpaceY = 5;
            for (let r = 0; r < wRows; r++) {
                for (let c = 0; c < wPerRow; c++) {
                    // Deterministic "lit?" — skip when (i*7 + r*3 + c) % 5 === 0
                    if ((i * 7 + r * 3 + c) % 5 === 0) continue;
                    const wx = bx + wPadX + c * (1 + wSpaceX);
                    const wy = by + wPadY + r * (1 + wSpaceY);
                    if (wy + 1 > by + bh - 2) continue; // don't draw windows past the bottom
                    ctx.fillStyle = '#d4b96a';
                    ctx.fillRect(Math.round(wx), Math.round(wy), 1, 1);
                    ctx.fillStyle = '#100a08';
                }
            }
            bx += bw;
            i++;
        }

        // Ground line — single dark pixel-row separating skyline from the
        // parchment band below, so the eye doesn't have to track where the
        // city ends and the GAME START callout begins.
        ctx.fillStyle = '#0a0606';
        ctx.fillRect(PANEL_X, GROUND_Y - 1, PANEL_W, 2);
    }

    // ── Game Frame ───────────────────────────────────────────────────────────

    renderFrame(game) {
        const { ctx } = this;
        ctx.imageSmoothingEnabled = false;
        ctx.clearRect(0, 0, CANVAS_PX, CANVAS_PX);

        this._scrollX = 0;
        this._scrollY = 0;
        if (game._animating) {
            const t = game._animProgress || 0;
            this._scrollX = (game._animToX - game._animFromX) * t * TILE_PX;
            this._scrollY = (game._animToY - game._animFromY) * t * TILE_PX;
        }

        // Screen shake (Phase F) — random offset applied to world rendering
        // only. Magnitude scales linearly with remaining time so the shake
        // decays to zero rather than ending abruptly. HUD is rendered after
        // the restore so it stays fixed on screen during the shake.
        const now = performance.now();
        const shakeRemaining = (game._screenShakeUntil ?? 0) - now;
        let shakeX = 0, shakeY = 0;
        if (shakeRemaining > 0) {
            const duration = shakeRemaining / 150; // rough normalize (0..~1.2)
            const decay = Math.min(1, duration);
            const mag = (game._screenShakeMagnitude ?? 0) * decay;
            shakeX = (Math.random() - 0.5) * mag * 2;
            shakeY = (Math.random() - 0.5) * mag * 2;
        }

        ctx.save();
        ctx.translate(shakeX, shakeY);

        this._drawTiles(game);
        this._drawContainers(game);
        this._drawGroundItems(game);
        this._drawEnemies(game);
        this._drawPlayer(game);

        // Floating damage numbers float above the world but under the HUD
        // so the HP panel + hotbar are never occluded by spammy combat.
        this._drawDamageNumbers(game);

        ctx.restore();

        // HUD — rendered AFTER restore so screen shake doesn't affect it
        this._drawHPPanel(game);
        this._drawZoneLabel(game);
        this._drawBuffBar(game);
        this._drawLogStrip(game);
        this._drawHotbar(game);

        // Subtle vignette border
        this._drawVignette();

        // Modals
        if (game.state === 'item_overlay')    this._drawItemOverlay(game);
        if (game.state === 'radial_menu')     this._drawRadialMenu(game);
        if (game.state === 'item_throw_dir')  this._drawThrowPrompt(game);
        if (game.state === 'item_give_dir')   this._drawThrowPrompt(game);
        if (game.state === 'win') this._drawWinOverlay(game);
    }

    // ── Tiles ────────────────────────────────────────────────────────────────

    _drawTiles(game) {
        const { ctx, half, sprites } = this;
        const sheet = sprites?.sewerTiles;
        const pad = 2;
        for (let vy = -pad; vy < VIEW_TILES + pad; vy++) {
            for (let vx = -pad; vx < VIEW_TILES + pad; vx++) {
                const wx = game.playerX - half + vx;
                const wy = game.playerY - half + vy;
                const px = vx * TILE_PX - this._scrollX;
                const py = vy * TILE_PX - this._scrollY;
                const id = game.map.getTile(wx, wy);
                const def = game.map.getTileDef(wx, wy);
                // Lookup chain: sewer ids 0-7 → TILE_SPRITE_MAP,
                // town ids 10-21 → TOWN_TILE_SPRITE_MAP,
                // circus/factory/graveyard ids 30+ → ZONE_TILE_SPRITE_MAP.
                // Disjoint id ranges so order doesn't matter, but explicit
                // chain keeps the resolution path readable.
                const ref = TILE_SPRITE_MAP[id] || TOWN_TILE_SPRITE_MAP[id] || ZONE_TILE_SPRITE_MAP[id];
                let ok = false;
                if (ref) {
                    if (ref.region) {
                        // Pixel-region based (for large exterior sheets)
                        const regionSheet = sprites?.[ref.sheet];
                        if (regionSheet?.loaded) {
                            ok = regionSheet.drawRegion(ctx, ref.x, ref.y, ref.w, ref.h, px, py, TILE_PX, TILE_PX);
                        }
                    } else {
                        // Grid-based (for sewer tileset)
                        const tileSheet = ref.sheet ? sprites?.[ref.sheet] : sheet;
                        if (tileSheet?.loaded) {
                            ok = tileSheet.drawFrame(ctx, ref.col, ref.row, px, py, TILE_PX, TILE_PX);
                        }
                    }
                }
                if (!ok) {
                    ctx.fillStyle = def.fallbackColor;
                    ctx.fillRect(px, py, TILE_PX, TILE_PX);
                }
            }
        }
    }

    // ── Containers ───────────────────────────────────────────────────────────
    //
    // Placeholder chest rendering: dark-brown box with a gold lid stripe.
    // When the chest has contents, a small gold pip floats in the center to
    // distinguish "ripe to loot" from "already emptied." Sprite art is a
    // polish-pass concern (step 7); the box reads at a glance and that's
    // enough for now.

    _drawContainers(game) {
        const { ctx, half } = this;
        for (const c of game.containers) {
            const vx = c.x - game.playerX + half;
            const vy = c.y - game.playerY + half;
            if (vx < -2 || vx > VIEW_TILES + 1 || vy < -2 || vy > VIEW_TILES + 1) continue;
            const px = vx * TILE_PX - this._scrollX;
            const py = vy * TILE_PX - this._scrollY;

            // Body
            ctx.fillStyle = '#5a3a1a';
            ctx.fillRect(px + 6, py + 10, TILE_PX - 12, TILE_PX - 16);
            // Lid stripe
            ctx.fillStyle = '#c4a050';
            ctx.fillRect(px + 6, py + 10, TILE_PX - 12, 4);
            // Outline
            ctx.strokeStyle = '#2a1a08';
            ctx.lineWidth = 1;
            ctx.strokeRect(px + 6, py + 10, TILE_PX - 12, TILE_PX - 16);

            // Contents indicator — up to three gold pips along the lid, one
            // per item up to a visual cap of 3. Lets the player watch the
            // chest fill as workers deposit, without needing to read the log.
            if (c.contents.length > 0) {
                const pips = Math.min(3, c.contents.length);
                ctx.fillStyle = '#ffdd44';
                const pipSize = 3;
                const pipGap = 2;
                const totalWidth = pips * pipSize + (pips - 1) * pipGap;
                const startX = px + (TILE_PX - totalWidth) / 2;
                for (let i = 0; i < pips; i++) {
                    ctx.fillRect(startX + i * (pipSize + pipGap), py + 11, pipSize, pipSize);
                }
            }
        }
    }

    // ── Ground Items ─────────────────────────────────────────────────────────

    _drawGroundItems(game) {
        const { ctx, half, sprites } = this;
        for (const item of game.groundItems) {
            const vx = item.x - game.playerX + half;
            const vy = item.y - game.playerY + half;
            if (vx < -2 || vx > VIEW_TILES + 1 || vy < -2 || vy > VIEW_TILES + 1) continue;
            const px = vx * TILE_PX - this._scrollX;
            const py = vy * TILE_PX - this._scrollY;

            // Try sprite from ITEM_SPRITES
            const spr = ITEM_SPRITES[item.type];
            let drawn = false;
            if (spr && sprites?.[spr.sheet]?.loaded) {
                drawn = sprites[spr.sheet].drawRegion(ctx, spr.x, spr.y, spr.w, spr.h, px + 4, py + 4, 24, 24);
            }

            if (!drawn) {
                const info = ITEM_COLORS[item.type] || { bg: '#aaa', letter: '?' };
                ctx.fillStyle = '#000000aa';
                ctx.fillRect(px + 9, py + 9, 16, 16);
                ctx.fillStyle = info.bg;
                ctx.fillRect(px + 8, py + 8, 16, 16);
                ctx.fillStyle = '#fff';
                ctx.font = 'bold 10px monospace';
                ctx.fillText(info.letter, px + 12, py + 20);
            }
        }
    }

    // ── Enemies ──────────────────────────────────────────────────────────────

    _drawEnemies(game) {
        const { ctx, half, sprites } = this;
        const now = performance.now();
        for (const e of game.enemies) {
            const vx = e.x - game.playerX + half;
            const vy = e.y - game.playerY + half;
            if (vx < -2 || vx > VIEW_TILES + 1 || vy < -2 || vy > VIEW_TILES + 1) continue;

            const isAlive = e.entity.isAlive();

            // Hit-flash + stagger (Phase C) only animate while alive —
            // corpses are static after death.
            const flashing = isAlive && (e._hitFlashUntil ?? 0) > now;
            const staggerRemaining = isAlive ? (e._staggerUntil ?? 0) - now : 0;
            const staggerProgress = staggerRemaining > 0 ? staggerRemaining / 80 : 0;
            const offsetX = staggerProgress > 0 ? (e._staggerDx ?? 0) * staggerProgress : 0;
            const offsetY = staggerProgress > 0 ? (e._staggerDy ?? 0) * staggerProgress : 0;

            const px = vx * TILE_PX - this._scrollX + offsetX;
            const py = vy * TILE_PX - this._scrollY + offsetY;

            // Sprite — same draw for alive and dead; the death state is
            // expressed via the gray tint overlay below, not via a different
            // sprite. Future polish swap could pull a fallen-character
            // sprite from the Kenney pack if one is appropriate.
            let ok = false;
            const info = ENEMY_SPRITES[e.type];
            if (info && sprites?.[info.sheet]?.loaded) {
                const col = info.static
                    ? info.col
                    : (((game._idleTick || 0) % 2 === 0) ? 0 : 2);
                ok = sprites[info.sheet].drawFrame(ctx, col, info.row, px + 4, py + 4, TILE_PX - 8, TILE_PX - 8);
            }
            if (!ok) {
                ctx.fillStyle = isAlive ? '#cc4433' : '#555';
                ctx.fillRect(px + 6, py + 6, TILE_PX - 12, TILE_PX - 12);
            }

            if (isAlive) {
                // Hit-flash overlay — alpha fades as the flash ages so it
                // pops on first frame and decays. Combined with the
                // damage-scaled duration set in main.js combatAttack,
                // heavier hits look heavier.
                if (flashing) {
                    const flashAge = now - (e._hitFlashUntil - 100);  // rough age proxy
                    const flashDur = (e._hitFlashUntil ?? now) - now; // remaining
                    const fade = Math.max(0, Math.min(1, flashDur / 120));
                    ctx.fillStyle = `rgba(255, 60, 40, ${0.55 * fade})`;
                    ctx.fillRect(px + 4, py + 4, TILE_PX - 8, TILE_PX - 8);
                }

                // HP bar above living enemy (with border)
                const frac = e.entity.hp / e.entity.maxHp;
                const bx = px + 4, by = py - 6, bw = TILE_PX - 8, bh = 5;
                ctx.fillStyle = '#000000cc';
                ctx.fillRect(bx - 1, by - 1, bw + 2, bh + 2);
                ctx.fillStyle = UI.hpBg;
                ctx.fillRect(bx, by, bw, bh);
                ctx.fillStyle = UI.hpRed;
                ctx.fillRect(bx, by, bw * frac, bh);

                // Debuff / buff badges — one-letter colored markers stacked
                // horizontally above the HP bar. Buffs (positive) show in
                // UI.buff green; debuffs (negative) show in UI.debuff red.
                // Letter = first character of the buff name uppercased
                // (Blind → 'B', future Poison → 'P', Stun → 'S').
                if (e.buffs && e.buffs.length > 0) {
                    const badgeY = py - 20;
                    let badgeX = px + 2;
                    for (const b of e.buffs) {
                        // Background pill — black so the colored letter stays
                        // readable over any sprite underneath
                        ctx.fillStyle = '#000000cc';
                        ctx.fillRect(badgeX, badgeY, 9, 10);
                        if (this.font) {
                            const letter = (b.name?.[0] ?? '?').toUpperCase();
                            const color = b.type === 'buff' ? UI.buff : UI.debuff;
                            this.font.drawText(ctx, letter, badgeX + 1, badgeY + 1, {
                                color, scale: 1,
                            });
                        }
                        badgeX += 11;
                    }
                }
            } else {
                // Corpse — gray tint overlay turns the sprite into a faded
                // version of itself, marking it as "defeated" without
                // requiring a separate corpse sprite. Combined with the
                // K.O. tag below, it reads as a clear "this enemy is done"
                // without removing them from the world entirely. Mother 3
                // and Persona both leave defeated enemies as visible body
                // markers; this is the cheap version of that move.
                ctx.fillStyle = 'rgba(60, 60, 60, 0.55)';
                ctx.fillRect(px + 4, py + 4, TILE_PX - 8, TILE_PX - 8);

                // K.O. tag below — small, faded, semi-respectful. The tag
                // is the player's permanent record of "you fought this
                // person here." Future merchant/loot features could read
                // the corpse and let the player pick it up.
                if (this.font) {
                    this.font.drawText(ctx, `[KO] ${e.type.toUpperCase()}`, px + TILE_PX / 2, py + TILE_PX - 2, {
                        color: '#9a8a78', scale: 1, align: 'center',
                    });
                }
            }
        }
    }

    // ── Floating damage numbers ──────────────────────────────────────────────
    //
    // Each particle floats upward and fades over its 600ms lifetime. The
    // particle stores its origin in tile-space so it tracks the camera
    // correctly if the player moves while the particle is alive.
    //
    // Rendering math: position offset is velocity × elapsed (in seconds);
    // alpha is the linear fade ramp (1 → 0) across lifetime. The text uses
    // a black drop-shadow so it's readable against any tile background.

    _drawDamageNumbers(game) {
        const { ctx, half } = this;
        const now = performance.now();
        for (const dn of game._damageNumbers) {
            const age = now - dn.bornAt;
            if (age >= dn.maxAge) continue; // expired (filtered next loop tick)

            const t = age / 1000; // seconds
            const vx = dn.tileX - game.playerX + half;
            const vy = dn.tileY - game.playerY + half;
            // stackSlot adds a fixed pixel offset per slot so per-source
            // dialogue stacks chat-window-style (newest at speaker, older
            // rising). Particles without stackSlot (damage numbers, event
            // words) get slot 0 = no offset, behavior unchanged.
            const STACK_LINE_PX = 14;
            const slotOffset = (dn.stackSlot ?? 0) * STACK_LINE_PX;
            const px = vx * TILE_PX + TILE_PX / 2 - this._scrollX + dn.vx * t;
            const py = vy * TILE_PX + TILE_PX / 4 - this._scrollY + dn.vy * t - slotOffset;

            const alpha = 1 - age / dn.maxAge;

            // Scale-on-spawn — elastic ease-out from 0.5× → 1.0× over the
            // first 100ms gives every number a satisfying "pop" entrance.
            // Past 100ms it sits at 1×; past 500ms it starts shrinking again
            // as it fades, like a deflating balloon.
            let scaleMul = 1;
            if (age < 100) {
                const p = age / 100;
                // Cubic ease-out from 0.5 → 1.0
                scaleMul = 0.5 + 0.5 * (1 - Math.pow(1 - p, 3));
            } else if (age > dn.maxAge - 150) {
                const p = (age - (dn.maxAge - 150)) / 150;
                scaleMul = 1 - 0.2 * p; // shrink slightly while fading out
            }

            // Bitmap font path — pixel-perfect text with a black outline that
            // tracks the scale. Falls back to canvas text if the font failed
            // to load (defensive; main.js logs a warn in that case).
            if (this.font) {
                // Map dn.size (8-20px historically) to a bitmap scale
                // (1=8px, 2=16px, 3=24px). Round to nearest integer scale
                // so the pixels stay aligned. The scale-on-spawn modulates
                // this within a per-particle range.
                const baseScale = Math.max(1, Math.round(dn.size / 8));
                const scale = Math.max(1, Math.round(baseScale * scaleMul));
                // Per-source dialogue particles (sourceRef) get NO outline —
                // they're already on a contrast-friendly parchment bubble.
                // Damage numbers / event words DO get an outline since they
                // float over varied tile backgrounds.
                const hasOutline = !dn.sourceRef;
                const colorWithAlpha = hexToRgba(dn.color, alpha);
                const shadow = hasOutline ? `rgba(0, 0, 0, ${alpha * 0.85})` : null;
                this.font.drawText(ctx, dn.text, px, py, {
                    color: colorWithAlpha,
                    scale,
                    align: 'center',
                    shadow,
                });
            } else {
                // Fallback path retained — system monospace, alpha-faded.
                ctx.font = `bold ${Math.round(dn.size * scaleMul)}px monospace`;
                ctx.textAlign = 'center';
                ctx.fillStyle = `rgba(0, 0, 0, ${alpha * 0.8})`;
                ctx.fillText(dn.text, px + 1, py + 1);
                ctx.fillStyle = hexToRgba(dn.color, alpha);
                ctx.fillText(dn.text, px, py);
            }
        }
        ctx.textAlign = 'left'; // reset for downstream HUD draws
    }

    // ── Player ───────────────────────────────────────────────────────────────

    _drawPlayer(game) {
        const { ctx, half, sprites } = this;
        const now = performance.now();

        // Hit-flash + stagger (Phase C) — same pattern as enemies, but
        // reading from game._playerHitFlashUntil et al.
        const flashing = (game._playerHitFlashUntil ?? 0) > now;
        const staggerRemaining = (game._playerStaggerUntil ?? 0) - now;
        const staggerProgress = staggerRemaining > 0 ? staggerRemaining / 80 : 0;
        const offsetX = staggerProgress > 0 ? (game._playerStaggerDx ?? 0) * staggerProgress : 0;
        const offsetY = staggerProgress > 0 ? (game._playerStaggerDy ?? 0) * staggerProgress : 0;

        const ppx = half * TILE_PX + offsetX;
        const ppy = half * TILE_PX + offsetY;

        // Kenney chars are single-frame per cell — no facing/animation rows.
        // PLAYER_SPRITE.col/row are read from sprites.js as the canonical
        // player cell. The previous LimeZu FACE/animation logic is parked
        // until/unless we get an animated Kenney character pack.
        let ok = false;
        if (sprites?.player?.loaded) {
            ok = sprites.player.drawFrame(
                ctx, PLAYER_SPRITE.col, PLAYER_SPRITE.row,
                ppx + 4, ppy + 4, TILE_PX - 8, TILE_PX - 8
            );
        }
        if (!ok) {
            ctx.fillStyle = '#44bb44';
            ctx.fillRect(ppx + 6, ppy + 6, TILE_PX - 12, TILE_PX - 12);
        }

        // Hit-flash overlay — red tint when the player just took damage.
        // Sharper alpha than the enemy flash since the player sprite tends
        // to be more visually prominent on a dark sewer floor.
        if (flashing) {
            ctx.fillStyle = 'rgba(255, 50, 30, 0.5)';
            ctx.fillRect(ppx + 4, ppy + 4, TILE_PX - 8, TILE_PX - 8);
        }
    }

    // ── HP Panel (top-left, parchment style) ─────────────────────────────────
    //
    // Three-resource stack: HP (red), MP (cyan), GP (gold card row). HP and
    // MP render as inset bars with a bitmap-font readout. GP renders as a
    // small "Gold Card" pill — an in-universe artifact (see
    // plans/gold-card.md): part rewards card, part bank account, part Town
    // ID. For the v1 HUD it's just a gold rectangle stamped "GP" with the
    // numeric balance trailing.
    //
    // Weapon stays at the bottom as a one-line summary.

    _drawHPPanel(game) {
        const { ctx } = this;
        const x = 6, y = 6, w = 170, h = 90;

        drawPanelSmall(ctx, x, y, w, h, this.uiSheet);

        const bx = x + 8, bw = w - 16, bh = 12;
        let by = y + 8;

        // — HP bar — always red per the violencetown palette (blood, not
        //   "danger" — the old green→red threshold was retired here).
        const hpFrac = game.playerHp / game.playerMaxHp;
        drawInset(ctx, bx, by, bw, bh);
        ctx.fillStyle = UI.hpRed;
        ctx.fillRect(bx + 1, by + 1, (bw - 2) * hpFrac, bh - 2);
        if (this.font) {
            this.font.drawText(ctx, `HP ${game.playerHp}/${game.playerMaxHp}`, bx + 3, by + 2, {
                color: '#fff', scale: 1,
            });
        }
        by += bh + 4;

        // — MP bar — cyan, ties to Skills (inert for now). The bar exists
        //   so the resource is legible the moment a skill ever spends from
        //   it; until then it sits at full.
        const mpFrac = (game.playerMp ?? game.playerMaxMp) / (game.playerMaxMp ?? 100);
        drawInset(ctx, bx, by, bw, bh);
        ctx.fillStyle = '#3a8ab0';
        ctx.fillRect(bx + 1, by + 1, (bw - 2) * mpFrac, bh - 2);
        if (this.font) {
            this.font.drawText(ctx, `MP ${game.playerMp ?? 0}/${game.playerMaxMp ?? 100}`, bx + 3, by + 2, {
                color: '#fff', scale: 1,
            });
        }
        by += bh + 4;

        // — Gold Card (GP) — a small dark-bordered gold pill with "GP" on
        //   the left edge and the balance trailing. The full Gold Card
        //   artifact (dollar-bill design with player face + town ID) lives
        //   in lore; this is the inline credit-card-strip rendering of it.
        const cardX = bx, cardY = by, cardW = bw, cardH = 14;
        ctx.fillStyle = '#2a2218';            // dark border (matches panel chrome)
        ctx.fillRect(cardX, cardY, cardW, cardH);
        ctx.fillStyle = UI.gold;              // gold body
        ctx.fillRect(cardX + 1, cardY + 1, cardW - 2, cardH - 2);
        // Dark "magnetic strip" on the left third — sells the credit-card
        // read at this size.
        ctx.fillStyle = '#1a1208';
        ctx.fillRect(cardX + 2, cardY + 2, 18, cardH - 4);
        if (this.font) {
            // "GP" stamped on the strip (white-on-dark)
            this.font.drawText(ctx, 'GP', cardX + 5, cardY + 3, {
                color: UI.gold, scale: 1,
            });
            // Balance on the gold face (dark text)
            this.font.drawText(ctx, `${game.gold ?? 0}`, cardX + cardW - 4, cardY + 3, {
                color: '#2a2218', scale: 1, align: 'right',
            });
        }
        by += cardH + 4;

        // — Weapon line at the bottom (informational; the hotbar carries
        //   the canonical inventory).
        const wpn = game.equipment.weapon;
        if (wpn && this.font) {
            const name = wpn.name.replace(/[\[\]]/g, '').toUpperCase();
            this.font.drawText(ctx, `${name}  ${wpn.damage} DMG`, x + 8, by, {
                color: UI.text, scale: 1,
            });
        }
    }

    // ── Zone Label (top center) ──────────────────────────────────────────────

    _drawZoneLabel(game) {
        const { ctx } = this;
        const label = game.map?.zoneName || '';
        const turnText = `T:${game.turn}`;
        const w = Math.max(100, label.length * 10 + 60);
        const px = (CANVAS_PX - w) / 2;

        drawPanelSmall(ctx, px, 4, w, 22, this.uiSheet);

        if (this.font) {
            this.font.drawText(ctx, label.toUpperCase(), CANVAS_PX / 2, 9, {
                color: UI.text, scale: 1, align: 'center',
            });
            // Turn counter right-aligned within the label panel
            this.font.drawText(ctx, turnText, px + w - 6, 9, {
                color: UI.dim, scale: 1, align: 'right',
            });
        }
    }

    // ── Buff Bar (top-right) ─────────────────────────────────────────────────

    _drawBuffBar(game) {
        if (game.buffs.length === 0) return;
        const { ctx } = this;
        const bw = 52, bh = 26, gap = 3;
        const total = game.buffs.length;
        const totalW = total * (bw + gap) - gap + 12;
        const px = CANVAS_PX - totalW - 6, py = 6;

        drawPanelSmall(ctx, px, py, totalW, bh + 12, this.uiSheet);

        for (let i = 0; i < total; i++) {
            const buff = game.buffs[i];
            const bx = px + 6 + i * (bw + gap), by = py + 6;

            // Inset background
            drawInset(ctx, bx, by, bw, bh);

            // Name + turns
            if (this.font) {
                const nameColor = buff.type === 'debuff' ? UI.hpRed : UI.hpGreen;
                this.font.drawText(ctx, buff.name.toUpperCase().slice(0, 5), bx + 3, by + 3, {
                    color: nameColor, scale: 1,
                });
                this.font.drawText(ctx, `${buff.turns}`, bx + bw - 4, by + 14, {
                    color: UI.gold, scale: 1, align: 'right',
                });
            }
        }
    }

    // ── In-canvas Log Strip (above hotbar) ──────────────────────────────────
    //
    // Persistent 3-slot rolling log rendered as a parchment strip above the
    // hotbar. Mirrors _log() messages from main.js's _logStripMessages ring
    // buffer (newest at end). Newest sits at the bottom of the strip (chat-
    // window convention); older messages dim with position so the eye lands
    // on the freshest line first. Hotbar tooltip is allowed to overlay this
    // strip via z-order — _drawHotbar runs after _drawLogStrip in _drawScene.
    //
    // Color per category uses the parchment-panel palette (UI.text base);
    // combat/pickup/gold tints make different message types visually distinct
    // without needing to read every line.

    _drawLogStrip(game) {
        const messages = game._logStripMessages;
        if (!messages || messages.length === 0) return;

        const { ctx } = this;
        const SX = 6;
        const SW = 300;
        const SH = 44;
        const HOTBAR_OY = CANVAS_PX - 42 - 20;
        const SY = HOTBAR_OY - SH - 6;

        drawPanelSmall(ctx, SX, SY, SW, SH, this.uiSheet);

        // Newest message bottom-aligned at line 3; older messages climb up.
        // Top-of-glyph y baselines (bitmap font draws from top-left).
        const baselines = [SY + 6, SY + 18, SY + 30];
        const alphas    = [0.5, 0.75, 1.0]; // oldest → newest position

        const visible = messages.slice(-3);              // last N entries
        const offset  = 3 - visible.length;              // top-align if fewer than 3

        for (let i = 0; i < visible.length; i++) {
            const m = visible[i];
            const slot = i + offset;
            const baseColor = this._logStripColor(m.category);
            const tintedColor = hexToRgba(baseColor, alphas[slot]);
            // Truncate to fit width — bitmap font is 8px/char at scale 1,
            // so SW(300) minus 16px padding = ~35 chars.
            let text = m.text;
            if (text.length > 35) text = text.slice(0, 34) + '~';
            if (this.font) {
                this.font.drawText(ctx, text, SX + 8, baselines[slot], {
                    color: tintedColor, scale: 1,
                });
            }
        }
    }

    // Map a log-strip message category to a parchment-palette tint. Falls
    // back to UI.text so unknown categories stay readable. Kept as its own
    // method so future categories slot in without touching _drawLogStrip.
    _logStripColor(category) {
        switch (category) {
            case 'combat':     return UI.hpRed;    // damage, deaths, fights
            case 'pickup':     return UI.hpGreen;  // items collected, gold
            case 'transition': return UI.gold;     // zone entries, milestones
            case 'system':
            default:           return UI.text;     // dark brown — default
        }
    }

    // ── Inventory Hotbar (bottom) ────────────────────────────────────────────

    _drawHotbar(game) {
        const { ctx, sprites } = this;
        const sw = 42, sh = 42, gap = 3;
        const count = 9;
        const totalW = count * (sw + gap) - gap + 16;
        const ox = (CANVAS_PX - totalW) / 2;
        const oy = CANVAS_PX - sh - 20;

        // Selected item tooltip above hotbar — name, description, and stats
        if (game.selectedSlot >= 0 && game.inventory[game.selectedSlot]) {
            const itemDef = game.inventory[game.selectedSlot].itemDef;
            const itemName = itemDef.name.replace(/[\[\]]/g, '');

            // Build stat line
            let statLine = '';
            if (itemDef.healAmount) statLine = `Heals ${itemDef.healAmount} HP`;
            else if (itemDef.damage) statLine = `${itemDef.useType === 'throw' ? 'Throw' : 'Melee'} ${itemDef.damage} dmg`;

            const desc = itemDef.description || '';
            const hasDesc = desc.length > 0;
            const hasStat = statLine.length > 0;
            const lines = 1 + (hasDesc ? 1 : 0) + (hasStat ? 1 : 0);
            const th = 10 + lines * 13;
            const tw = Math.max(itemName.length * 7 + 16, hasDesc ? Math.min(desc.length * 5.5 + 16, 300) : 0, 120);
            const tx = (CANVAS_PX - tw) / 2;
            const ty = oy - th - 6;

            // Item tooltip uses the dark variant so it reads as an
            // overlay above the parchment hotbar without clashing.
            drawPanelSmall(ctx, tx, ty, tw, th, this.uiSheet, 'dark');

            let lineY = ty + 4;

            // Name (uppercased for bitmap-font readability emphasis)
            if (this.font) {
                this.font.drawText(ctx, itemName.toUpperCase(), CANVAS_PX / 2, lineY, {
                    color: UI.gold, scale: 1, align: 'center',
                });
            }
            lineY += 11;

            // Stat line
            if (hasStat && this.font) {
                const statColor = itemDef.healAmount ? '#44ff88' : '#ffaa44';
                this.font.drawText(ctx, statLine.toUpperCase(), CANVAS_PX / 2, lineY, {
                    color: statColor, scale: 1, align: 'center',
                });
                lineY += 11;
            }

            // Description — fits more chars at 8px-per-glyph than the old 5.5px estimate
            if (hasDesc && this.font) {
                const maxChars = Math.floor((tw - 12) / 8);
                const truncated = desc.length > maxChars ? desc.slice(0, maxChars - 2) + '..' : desc;
                this.font.drawText(ctx, truncated, CANVAS_PX / 2, lineY, {
                    color: UI.dim || '#8a8070', scale: 1, align: 'center',
                });
            }
        }

        // Parchment background strip
        drawPanelSmall(ctx, ox, oy - 4, totalW, sh + 12, this.uiSheet);

        // Selected-slot pulse — same 2Hz heartbeat as the radial menu's
        // active slice so the two highlight surfaces feel consistent.
        const selPulse = 0.5 + 0.5 * Math.sin(performance.now() / 1000 * Math.PI * 2);

        for (let i = 0; i < count; i++) {
            const sx = ox + 8 + i * (sw + gap);
            const sy = oy + 2;
            const stack = game.inventory[i];
            const sel = game.selectedSlot === i;
            const isEmpty = !stack;

            // Slot frame — selected gets the parchment "glow" variant +
            // pulsing gold halo; unselected gets a flat dark inset.
            if (sel) {
                // Outer halo (gold, swelling with pulse)
                ctx.fillStyle = `rgba(212, 185, 106, ${0.3 + 0.4 * selPulse})`;
                ctx.fillRect(sx - 2, sy - 2, sw + 4, sh + 4);
            }
            drawInset(ctx, sx, sy, sw, sh);

            // Selected highlight border (always crisp, on top of the halo)
            if (sel) {
                ctx.strokeStyle = UI.gold;
                ctx.lineWidth = 2;
                ctx.strokeRect(sx - 1, sy - 1, sw + 2, sh + 2);
            }

            // Empty-slot opacity nudge — empty slots render at ~70%
            // opacity so the filled slots draw the eye first.
            const slotAlpha = isEmpty ? 0.7 : 1.0;
            const prevAlpha = ctx.globalAlpha;
            ctx.globalAlpha = slotAlpha;

            // Key number (top-left corner of slot)
            if (this.font) {
                this.font.drawText(ctx, `${i + 1}`, sx + 2, sy + 2, {
                    color: sel ? UI.gold : '#5a5040', scale: 1,
                });
            }

            // Reset alpha after the key number; item draw decides for itself.
            ctx.globalAlpha = prevAlpha;

            // Item
            if (stack) {
                // Try sprite
                const spr = ITEM_SPRITES[stack.itemDef.id];
                let drawn = false;
                if (spr && sprites?.[spr.sheet]?.loaded) {
                    drawn = sprites[spr.sheet].drawRegion(ctx, spr.x, spr.y, spr.w, spr.h, sx + 7, sy + 9, 24, 24);
                }
                if (!drawn) {
                    const info = ITEM_COLORS[stack.itemDef.id] || { bg: '#888', letter: '?' };
                    ctx.fillStyle = info.bg;
                    ctx.fillRect(sx + 9, sy + 11, 22, 22);
                    if (this.font) {
                        this.font.drawText(ctx, info.letter, sx + 16, sy + 17, {
                            color: '#fff', scale: 2,
                        });
                    }
                }

                // Stack count (bottom-right)
                if (stack.count > 1) {
                    // Dark backing for readability
                    ctx.fillStyle = '#000000aa';
                    ctx.fillRect(sx + sw - 16, sy + sh - 11, 14, 10);
                    if (this.font) {
                        this.font.drawText(ctx, `${stack.count}`, sx + sw - 3, sy + sh - 10, {
                            color: UI.gold, scale: 1, align: 'right',
                        });
                    }
                }
            }
        }
    }

    // ── Item Overlay ─────────────────────────────────────────────────────────

    _drawItemOverlay(game) {
        const { ctx, half } = this;
        const ui = this.uiSheet;
        const cx = half * TILE_PX + TILE_PX / 2;
        const cy = half * TILE_PX + TILE_PX / 2;

        // Phase D: slide-in animation. Options lerp from the player tile
        // center → their final positions over 80ms with ease-out, while
        // the panel alpha and option opacity ramp 0 → 1. This is the
        // "snappy" feel — the menu doesn't appear, it *arrives*.
        const now = performance.now();
        const openAt = game._overlayOpenedAt ?? now;
        const rawT = Math.min(1, Math.max(0, (now - openAt) / 80));
        const t = easeOutCubic(rawT);

        ctx.fillStyle = `rgba(0,0,0,${0.5 * t})`;
        ctx.fillRect(0, 0, CANVAS_PX, CANVAS_PX);
        this._drawPlayer(game);

        const opts = game.overlayOptions;
        const finalPos = {
            up:    { x: cx - 44, y: cy - TILE_PX - 38 },
            down:  { x: cx - 44, y: cy + TILE_PX + 8 },
            left:  { x: cx - TILE_PX - 84, y: cy - 16 },
            right: { x: cx + TILE_PX + 8,  y: cy - 16 },
        };
        // ASCII fallback arrows since the bitmap font is plain ASCII —
        // ^ v < > read instantly as directional cues.
        const arr = { up: '^', down: 'V', left: '<', right: '>' };
        // Lerp source — center of the player tile, slightly above
        const src = { x: cx - 44, y: cy - 16 };

        const prevAlpha = ctx.globalAlpha;
        ctx.globalAlpha = t;
        for (const [dir, opt] of Object.entries(opts)) {
            if (!finalPos[dir]) continue;
            const fp = finalPos[dir];
            const px = src.x + (fp.x - src.x) * t;
            const py = src.y + (fp.y - src.y) * t;
            const w = 88, h = 32;

            drawPanelSmall(ctx, px, py, w, h, this.uiSheet);

            if (this.font) {
                const label = opt.label.toUpperCase();
                this.font.drawText(ctx, `${arr[dir]} ${label}`, px + 8, py + 12, {
                    color: UI.text, scale: 1,
                });
            }
        }
        ctx.globalAlpha = prevAlpha;
    }

    // ── Radial Menu (Omnitrix-style combat wheel) ────────────────────────────
    //
    // Six-slice inner wheel + on-demand outer arc for sub-options. The active
    // slice (game.radialInnerIndex) gets a gold highlight; if it's a category
    // with sub-options (Throw / Give / Skill), the outer arc renders showing
    // those options laid out along the same hemisphere as the inner slice.
    // When game.radialDrilled is true, the cursor is on the outer arc and the
    // sub-slice gets the highlight instead.

    _drawRadialMenu(game) {
        const { ctx, half } = this;
        const cx = half * TILE_PX + TILE_PX / 2;
        const cy = half * TILE_PX + TILE_PX / 2;

        // Slide-in animation (Phase D convention — 80ms ease-in opacity)
        const elapsed = performance.now() - (game._overlayOpenedAt ?? 0);
        const t = Math.min(1, elapsed / 80);

        // Slice order kept in sync with main.js RADIAL_SLICES module const.
        // Renderer keeps its own copy because the canvas drawing layer
        // shouldn't import from the game-logic module.
        const slices = ['Attack', 'Skill', 'Throw', 'Give', 'Run', 'Defend'];
        const N = slices.length;
        const sliceAngle = (Math.PI * 2) / N;

        // Inner wheel: radius from 36 (just outside the 32px player tile) to 80
        const rInner0 = 36;
        const rInner1 = 80;
        // Outer arc (sub-wheel): radius from 84 to 120
        const rOuter0 = 84;
        const rOuter1 = 120;

        // Helper: center angle of slice i in the wheel's LOCAL frame, with 12
        // o'clock = -π/2 in canvas coords (y axis flipped, angles clockwise).
        // The wheel's outer rotation transform maps local → world.
        const sliceCenterAngle = (i) => i * sliceAngle - Math.PI / 2;

        const prevAlpha = ctx.globalAlpha;
        ctx.globalAlpha = t;

        // Current rotation from the ease-out lerp. Game owns the math so
        // animation state is single-sourced.
        const innerRotation = game._currentRadialRotation
            ? game._currentRadialRotation()
            : -sliceAngle * (game.radialInnerIndex ?? 0);

        // ── Inner wheel (slices + labels) ────────────────────────────────────
        // Wrap the entire wheel draw in a rotation transform so the wheel
        // itself spins around the player center. Labels rotate WITH their
        // slices via per-label ctx.rotate — combined with the wheel rotation,
        // the label of the slice currently at 12 o'clock ends up upright
        // and the slice opposite (6 o'clock) is upside-down. That's the
        // chosen design ("Rotate with the wheel").
        ctx.save();
        ctx.translate(cx, cy);
        ctx.rotate(innerRotation);
        ctx.translate(-cx, -cy);

        // Active-slice pulse — a 2Hz sine wave on alpha + line width gives
        // the highlighted slice a slow heartbeat. Subtle enough to read as
        // ambient state (not as a warning), strong enough to draw the eye.
        // Uses performance.now() so it animates while the particle loop
        // pump (started by _openRadialMenu) is running.
        const pulse = 0.5 + 0.5 * Math.sin(performance.now() / 1000 * Math.PI * 2);

        // Draw slice wedges (local frame — the rotate above maps them to world)
        for (let i = 0; i < N; i++) {
            const a0 = sliceCenterAngle(i) - sliceAngle / 2;
            const a1 = sliceCenterAngle(i) + sliceAngle / 2;
            const isActive = !game.radialDrilled && i === game.radialInnerIndex;

            ctx.beginPath();
            ctx.arc(cx, cy, rInner1, a0, a1);
            ctx.arc(cx, cy, rInner0, a1, a0, true);
            ctx.closePath();
            ctx.fillStyle = isActive ? UI.gold : UI.panelBg;
            ctx.fill();
            // Active slice gets a brighter trim that swells with the pulse.
            ctx.strokeStyle = isActive
                ? `rgba(240, 215, 130, ${0.7 + 0.3 * pulse})`
                : UI.panelBorder;
            ctx.lineWidth = isActive ? 3 + pulse : 1;
            ctx.stroke();
        }

        // Inner hub — a small dark disk centered on the player tile, with a
        // gold dot in its center. Reads as the wheel's pivot point and hides
        // the visual seam where the rotation transform meets the player sprite.
        ctx.beginPath();
        ctx.arc(cx, cy, rInner0 - 4, 0, Math.PI * 2);
        ctx.fillStyle = UI.panelBgDark;
        ctx.fill();
        ctx.strokeStyle = UI.panelBorder;
        ctx.lineWidth = 1;
        ctx.stroke();
        ctx.fillStyle = UI.gold;
        ctx.fillRect(cx - 1, cy - 1, 2, 2);

        // Draw slice labels, each with a per-label rotation so the active
        // slice's text is upright when it lands at 12 o'clock under the
        // pointer. Math: label-i's local rotation = i*sliceAngle. Combined
        // with the wheel's world rotation R = -activeIndex*sliceAngle, the
        // total world rotation of label-i is (i - activeIndex)*sliceAngle —
        // which is 0 (upright) when i == activeIndex.
        const rLabel = (rInner0 + rInner1) / 2;
        for (let i = 0; i < N; i++) {
            const ang = sliceCenterAngle(i);
            const lx = cx + Math.cos(ang) * rLabel;
            const ly = cy + Math.sin(ang) * rLabel;
            ctx.save();
            ctx.translate(lx, ly);
            ctx.rotate(i * sliceAngle); // per-label rotation (see math comment)
            // Bitmap font draws from top-left; nudge by half a glyph width/height
            // so the visual center of the text sits at (0,0) in the rotated frame.
            if (this.font) {
                this.font.drawText(ctx, slices[i].toUpperCase(), 0, -4, {
                    color: UI.text, scale: 1, align: 'center',
                });
            }
            ctx.restore();
        }

        ctx.restore(); // pop inner wheel rotation

        // ── Sub-wheel (outer arc) — same rotating-wheel treatment ────────────
        const cat = slices[game.radialInnerIndex];
        const subCapable = cat === 'Attack' || cat === 'Throw' || cat === 'Give' || cat === 'Skill';
        if (subCapable) {
            const subOptions = game._radialSubItems ? game._radialSubItems(cat) : [];
            const subLabels = subOptions.length > 0
                ? subOptions.map(o => o.label)
                : ['—'];
            const subItems = subOptions;

            const M = subLabels.length;
            // Sub-arc slice size — kept in sync with main.js _animateSubRotation
            // so the rotation math matches the layout math exactly.
            const span = Math.min(M * sliceAngle, Math.PI);
            const subSliceAngle = span / M;
            // Sub-slice layout (parallel to inner wheel): slice j is centered
            // at angle -π/2 + j*subSliceAngle in the LOCAL frame. With
            // subRotation = -subSliceAngle * subIndex applied, the SELECTED
            // sub-slice lands at -π/2 (12 o'clock) under the pointer.
            const subCenter = (j) => -Math.PI / 2 + j * subSliceAngle;

            const subRotation = game._currentRadialSubRotation
                ? game._currentRadialSubRotation()
                : -subSliceAngle * (game.radialSubIndex?.[cat] ?? 0);

            ctx.save();
            ctx.translate(cx, cy);
            ctx.rotate(subRotation);
            ctx.translate(-cx, -cy);

            // Sub-wheel wedges
            for (let j = 0; j < M; j++) {
                const a0 = subCenter(j) - subSliceAngle / 2;
                const a1 = subCenter(j) + subSliceAngle / 2;
                const isSubActive = game.radialDrilled && j === (game.radialSubIndex?.[cat] ?? 0);

                ctx.beginPath();
                ctx.arc(cx, cy, rOuter1, a0, a1);
                ctx.arc(cx, cy, rOuter0, a1, a0, true);
                ctx.closePath();
                ctx.fillStyle = isSubActive ? UI.gold : (subItems.length === 0 ? UI.panelBgDark : UI.panelBg);
                ctx.fill();
                ctx.strokeStyle = UI.panelBorder;
                ctx.lineWidth = isSubActive ? 3 : 1;
                ctx.stroke();
            }

            // Sub-wheel labels — same per-label upright-at-pointer math as
            // the inner wheel: label-j gets local rotation j*subSliceAngle so
            // the selected sub-slice's text is upright at 12 o'clock.
            const subColor = subItems.length === 0 ? UI.textLight : UI.text;
            const rSubLabel = (rOuter0 + rOuter1) / 2;
            for (let j = 0; j < M; j++) {
                const ang = subCenter(j);
                const lx = cx + Math.cos(ang) * rSubLabel;
                const ly = cy + Math.sin(ang) * rSubLabel;
                ctx.save();
                ctx.translate(lx, ly);
                ctx.rotate(j * subSliceAngle);
                if (this.font) {
                    this.font.drawText(ctx, subLabels[j].toUpperCase(), 0, -4, {
                        color: subColor, scale: 1, align: 'center',
                    });
                }
                ctx.restore();
            }

            ctx.restore(); // pop sub-wheel rotation
        }

        // ── Decorative outer ring (OUTSIDE any rotation) ────────────────────
        // A faint gold ring just past the outer-arc radius, with 8 small
        // accent dots evenly spaced around it. The ring gives the wheel a
        // formal "summoned" feel — Persona-coded chrome around the spinning
        // combat menu — without competing visually with the slices themselves.
        const rRing = (game.radialDrilled ? rOuter1 : rInner1) + 6;
        ctx.beginPath();
        ctx.arc(cx, cy, rRing, 0, Math.PI * 2);
        ctx.strokeStyle = `rgba(212, 185, 106, ${0.4 + 0.2 * pulse})`;
        ctx.lineWidth = 1;
        ctx.stroke();
        for (let k = 0; k < 8; k++) {
            const a = (k / 8) * Math.PI * 2 - Math.PI / 2;
            const dx = cx + Math.cos(a) * rRing;
            const dy = cy + Math.sin(a) * rRing;
            ctx.fillStyle = UI.gold;
            ctx.fillRect(Math.round(dx) - 1, Math.round(dy) - 1, 2, 2);
        }

        // ── Static pointer triangle at 12 o'clock (OUTSIDE any rotation) ────
        // Small gold triangle pointing DOWN at the wheel, anchored above the
        // wheel's top edge. Drawn after restoring rotations so it never spins
        // with the wheel — its fixed position is what makes the spinning-wheel
        // metaphor work.
        const tipY = cy - rInner1 - 4;
        const baseY = cy - rInner1 - 14;
        ctx.beginPath();
        ctx.moveTo(cx, tipY);            // tip pointing down at the wheel
        ctx.lineTo(cx - 7, baseY);       // top-left
        ctx.lineTo(cx + 7, baseY);       // top-right
        ctx.closePath();
        ctx.fillStyle = UI.gold;
        ctx.fill();
        ctx.strokeStyle = UI.panelBorder;
        ctx.lineWidth = 1;
        ctx.stroke();

        // Restore default text alignment for whatever renders next
        ctx.textAlign = 'left';
        ctx.textBaseline = 'alphabetic';
        ctx.globalAlpha = prevAlpha;
    }

    // ── Throw Prompt ─────────────────────────────────────────────────────────

    _drawThrowPrompt(game) {
        const { ctx, half } = this;
        const cx = half * TILE_PX + TILE_PX / 2;
        const cy = half * TILE_PX + TILE_PX / 2;

        // ASCII arrows (the bitmap font is plain ASCII). ^ v < > read as
        // direction immediately and stay crisp at scale 2.
        const dirs = [
            { x: cx - 16, y: cy - TILE_PX - 18, l: '^' },
            { x: cx - 16, y: cy + TILE_PX + 2,  l: 'V' },
            { x: cx - TILE_PX - 18, y: cy - 16, l: '<' },
            { x: cx + TILE_PX + 2,  y: cy - 16, l: '>' },
        ];

        for (const d of dirs) {
            // 32×32 throw targets stay with the flat-fill fallback since
            // drawPanelSmall thresholds the 9-slice at 64px (corners
            // would overlap and degenerate at smaller sizes).
            drawPanelSmall(ctx, d.x, d.y, 32, 32, this.uiSheet);
            if (this.font) {
                this.font.drawText(ctx, d.l, d.x + 16, d.y + 8, {
                    color: UI.text, scale: 2, align: 'center',
                });
            }
        }
    }

    // ── Win Overlay ──────────────────────────────────────────────────────────

    _drawWinOverlay(game) {
        const { ctx } = this;
        const ui = this.uiSheet;

        ctx.fillStyle = 'rgba(0,0,0,0.6)';
        ctx.fillRect(0, 0, CANVAS_PX, CANVAS_PX);

        const w = 280, h = 120;
        const px = (CANVAS_PX - w) / 2, py = (CANVAS_PX - h) / 2;

        // Win overlay uses the glow variant — a brighter gold trim that
        // reads as a celebratory frame around the BOSS ROOM REACHED text.
        if (ui?.loaded) {
            drawPanelBig(ctx, ui, px, py, w, h, 'glow');
        } else {
            drawPanelSmall(ctx, px, py, w, h);
        }

        if (this.font) {
            this.font.drawText(ctx, 'BOSS ROOM REACHED', CANVAS_PX / 2, py + 36, {
                color: UI.panelBorder, scale: 2, align: 'center',
            });
            this.font.drawText(ctx, `${game.turn} TURNS`, CANVAS_PX / 2, py + 68, {
                color: UI.text, scale: 1, align: 'center',
            });
            this.font.drawText(ctx, 'PRESS N FOR NEW GAME', CANVAS_PX / 2, py + 90, {
                color: UI.textLight, scale: 1, align: 'center',
            });
        }
    }

    // ── Vignette (subtle edge darkening) ────────────────────────────────────

    _drawVignette() {
        const { ctx } = this;
        const s = CANVAS_PX;
        const g = ctx.createRadialGradient(s/2, s/2, s * 0.35, s/2, s/2, s * 0.55);
        g.addColorStop(0, 'rgba(0,0,0,0)');
        g.addColorStop(1, 'rgba(0,0,0,0.3)');
        ctx.fillStyle = g;
        ctx.fillRect(0, 0, s, s);
    }

    // ── Flash ────────────────────────────────────────────────────────────────

    flash(color = 'rgba(200,50,20,0.3)') {
        this.ctx.fillStyle = color;
        this.ctx.fillRect(0, 0, CANVAS_PX, CANVAS_PX);
    }
}

// ── Color util ──────────────────────────────────────────────────────────────
//
// Convert a hex color (#rrggbb) and an alpha (0..1) to an rgba string. Used
// by the damage-number renderer to apply per-frame alpha fades without
// needing to pre-compute rgba strings for every brightness step.

function hexToRgba(hex, alpha) {
    if (!hex || hex[0] !== '#') return `rgba(255,255,255,${alpha})`;
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return `rgba(${r},${g},${b},${alpha})`;
}

// Ease-out cubic — fast at the start, gentle at the end. The right curve
// for "appearing" animations like menu slides: the motion looks decisive
// (it commits early) and lands softly (no harsh stop).
function easeOutCubic(t) {
    return 1 - Math.pow(1 - t, 3);
}
